services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tourism
    ports:
      - "5433:5432"

  webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
      AIRFLOW__WEBSERVER__WEB_SERVER_PORT: "8080"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:1234@postgres:5432/tourism
    volumes:
      - ./dags:/opt/airflow/dags
      - ./notebooks:/opt/airflow/notebooks
      - ./airflow.cfg:/opt/airflow/airflow.cfg
      - ./webserver_config.py:/opt/airflow/webserver_config.py
    ports:
      - "8080:8080"

networks:
  default:
    name: eu_tourism_etl
